# Generated by Django 4.0 on 2022-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.CharField(default='', max_length=20)),
                ('room', models.IntegerField(default=0)),
                ('Guardian_name', models.CharField(max_length=100)),
                ('Guardian_contact', models.CharField(max_length=20)),
                ('guardian_addrss', models.CharField(max_length=200)),
                ('payment_staus', models.BooleanField()),
                ('registration_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='static/profile_image')),
            ],
        ),
    ]
