# Generated by Django 4.0 on 2022-04-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_user_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customer',
        ),
    ]
