# Generated by Django 4.0 on 2022-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='other', max_length=30),
        ),
    ]
