# Generated by Django 4.0 on 2022-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Not Mentioned', max_length=30),
        ),
    ]
