# Generated by Django 4.0 on 2022-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_customer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_image',
            field=models.ImageField(default='static/profile_image/avatar1.png', upload_to='static/profile_image'),
        ),
    ]
