# Generated by Django 4.0 on 2022-05-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_alter_customer_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_capacity', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='customer_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_Date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('allow_installment', models.BooleanField(default=True)),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.rooms'),
        ),
    ]
