# Generated by Django 4.0 on 2022-05-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_rooms_customer_fee_alter_customer_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='room',
        ),
    ]
