# Generated by Django 4.0 on 2022-05-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_remove_customer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.rooms'),
            preserve_default=False,
        ),
    ]
