# Generated by Django 4.0 on 2022-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_customer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
