# Generated by Django 4.0 on 2022-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='guardian_addrss',
        ),
        migrations.AddField(
            model_name='customer',
            name='food_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
