# Generated by Django 4.0 on 2022-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_remove_customer_guardian_addrss_customer_food_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('complian_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('complain_status', models.BooleanField(default=False)),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_price',
            field=models.IntegerField(default=6000),
        ),
    ]
