# Generated by Django 4.0 on 2022-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_complain_alter_rooms_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
