# Generated by Django 4.0 on 2022-06-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_customer_fee_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_fee',
            old_name='fee_id',
            new_name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer_fee',
            name='id',
        ),
        migrations.AddField(
            model_name='customer_fee',
            name='user_id',
            field=models.AutoField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
