# Generated by Django 4.0 on 2022-06-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_rename_fee_id_customer_fee_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_fee',
            old_name='user_id',
            new_name='fee_id',
        ),
    ]
