# Generated by Django 4.0 on 2022-06-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_remove_customer_payment_staus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='student_id',
        ),
        migrations.AddField(
            model_name='complain',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hostel.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_status',
            field=models.BooleanField(default=True),
        ),
    ]
