# Generated by Django 4.0 on 2022-06-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_remove_complain_student_id_complain_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('reply', models.BooleanField()),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.complain')),
            ],
        ),
    ]
