# Generated by Django 4.0 on 2022-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0025_customer_stay_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='date',
            field=models.DateTimeField(default='2022-06-06'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='detail',
            field=models.TextField(max_length=500),
        ),
    ]
