# Generated by Django 4.0 on 2022-06-05 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0026_complain_date_alter_complain_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 0, 46, 46, 54955)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stay_from',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
