# Generated by Django 4.0 on 2022-06-06 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0027_alter_complain_date_alter_customer_stay_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
